import { SECTION_NAVIGATION_DURATION_SECONDS } from "../../../utils/sectionNavigationMotion.js";

const SCROLL_STEP_DURATION_SECONDS = SECTION_NAVIGATION_DURATION_SECONDS;
const WHEEL_GESTURE_THRESHOLD_PX = 32;
const WHEEL_GESTURE_IDLE_MS = 180;
const SCROLL_SETTLE_DELAY_MS = 180;
const TOUCH_SWIPE_THRESHOLD_PX = 48;
const TOUCH_VERTICAL_DOMINANCE = 1.2;
const WHEEL_VERTICAL_DOMINANCE = 1.2;
const STATEMENT_PANEL_INDEX = 3;
const FEATURED_PROJECT_SELECTOR = "[data-featured-project-panel]";
const FEATURED_IMAGE_GALLERY_SELECTOR = "[data-featured-image-gallery]";
const CONTENT_TITLE_SCOPE_SELECTOR = "[data-content-title-scope]";
const FEATURED_PROJECT_EDGE_TOLERANCE_PX = 2;
const FEATURED_EXPANSION_SMOOTH_MIN_SECONDS = 0.06;
const FEATURED_EXPANSION_SMOOTH_MAX_SECONDS = 0.16;

export {
  CONTENT_TITLE_SCOPE_SELECTOR,
  FEATURED_EXPANSION_SMOOTH_MAX_SECONDS,
  FEATURED_EXPANSION_SMOOTH_MIN_SECONDS,
  FEATURED_IMAGE_GALLERY_SELECTOR,
  FEATURED_PROJECT_EDGE_TOLERANCE_PX,
  FEATURED_PROJECT_SELECTOR,
  SCROLL_SETTLE_DELAY_MS,
  SCROLL_STEP_DURATION_SECONDS,
  STATEMENT_PANEL_INDEX,
  TOUCH_SWIPE_THRESHOLD_PX,
  TOUCH_VERTICAL_DOMINANCE,
  WHEEL_GESTURE_IDLE_MS,
  WHEEL_GESTURE_THRESHOLD_PX,
  WHEEL_VERTICAL_DOMINANCE,
};
